version: '3'
services:
    jdbc-jsp-mysql:
        image:
            jdbc-jsp-mysql:0.0.7-SNAPSHOT
        ports:
         - 0080:8080
        environment:
            spring.datasource.url: "jdbc:mysql://mysql:3306/mysql_database?useSSL=false"
            
    mysql:
        image:
            mysql:latest
        ports:
        - 3305:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            